default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    args: ["--ignore=E501,BLK100,E203,E402"]
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: python -m unittest
        language: system
        pass_filenames: false
