default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Use the ref you want to point at
    hooks:
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: python -m unittest
        language: system
        pass_filenames: false
