[tool.coverage.run]
branch = true
source = ["."]
omit = ["*test*"]

[tool.coverage.report]
exclude_also = ["^if __name__ == .__main__.:$", "^if TYPE_CHECKING:$"]
omit = ["*test*"]

[tool.isort]
profile = "black"
line_length = 88
known_firstparty = ["cttexpress"]
